blogApp/urls.py
from django.urls import path
from . import views

'''
新建 urls.py
'''
app_name = 'blog'
urlpatterns = [
    path('index', views.index, name='index'),
    path('detail', views.detail, name='dt'),
    path('page', views.PageView.as_view(), name='page'),
    # path('<int:question_id>/', views.dt, name='detail'),
    path('<int:pk>/', views.DtView.as_view(), name='detail'),     # 使用通用视图
    # path('results/<int:question_id>', views.results, name='result'),
    path('results/<int:pk>', views.ResultsView.as_view(), name='result'),
    path('vote/<int:question_id>', views.vote, name='vote'),
]

myDjangoProject/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blogApp.urls'))       # 加入
]

blogApp/models.py
from django.db import models

# Create your models here.
import datetime
from django.utils import timezone


class User(models.Model):
    user_name = models.CharField(max_length=50)
    age = models.IntegerField(default=10)
    sex = models.CharField(max_length=10)

    def __str__(self):
        return self.user_name

    def calc(self, x, y):
        return x <= 5 <= y


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    # 下面3行是为了在后台设置（admin.py）list_display更加友好的展示 was_published_recently 此列
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

blogApp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Question, Choice
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.views import generic

# Create your views here.
def index(request):
    text = {'text': 'World'}
    return render(request, 'blogApp/index.html', {'t': text})

def detail(req):
    return render(req, 'blogApp/detail.html')


class PageView(generic.ListView):
    template_name = 'blogApp/page.html'
    '''
    对于 ListView， 自动生成的 context 变量是 question_list。
    为了覆盖这个行为，我们提供 context_object_name 属性，表示我们想使用 content
    '''
    context_object_name = 'content'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]

# DetailView 期望从 URL 中捕获名为 "pk" 的主键值，所以我们为通用视图把 question_id 改成 pk
class DtView(generic.DetailView):
    model = Question
    '''
    对于 DetailView ， question 变量会自动提供—— 因为我们使用 Django 的模型 (Question)，
     Django 能够为 context 变量决定一个合适的名字
    '''
    template_name = 'blogApp/dt.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'blogApp/results.html'

def page(request):
    latest_question_list = Question.objects.order_by('-pub_date')[0:5]
    return render(request, 'blogApp/page.html', {'content': latest_question_list})

def dt(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'blogApp/dt.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'blogApp/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'blogApp/dt.html', {'question': question, 'message_error': 'no data'})
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('blog:result', args=(question_id,)))

blogApp/templates/blogApp/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Detail</h1>
</body>
</html>

blogApp/templates/blogApp/dt.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
</head>
<body>
<h1>{{ question.id }} - {{ question.question_text }} - {{ question.pub_date }}</h1>

<ul>

</ul>

{% if message_error %}
    <p><strong>{{ message_error }}</strong></p>
{% endif %}

<form action="{% url 'blog:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for c in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ c.id }}"/>
        <label for="choice{{ forloop.counter }}">{{ c.choice_text }}</label><br>
    {% endfor %}

    <input type="submit" value="Vote">
</form>
</body>
</html>

blogApp/templates/blogApp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'blogApp/css/style.css' %}" />
    <title>Title</title>
</head>
<body>
<h1>
    <a href="{% url 'blog:dt' %}">
        Hello {{ t.text }}
    </a>
</h1>
</body>
</html>

blogApp/templates/blogApp/page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'blogApp/css/style.css' %}">
    <title>Page</title>
</head>
<body>
{% if content %}
    <ul>
        {% for q in content %}
            <li>
                {{ forloop.counter }} <a href="{% url 'blog:detail' q.id %}">{{ q.question_text }}</a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No dates</p>
{% endif %}
</body>
</html>

blogApp/templates/blogApp/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Results</title>
</head>
<body>
<h1>{{ question.id }} - {{ question.question_text }} - {{ question.pub_date }}</h1>

<ul>
    {% for c in question.choice_set.all %}
        <li>
        {{ c.choice_text }} -- {{ c.votes }} vote{{ c.votes | pluralize }}
        </li>
    {% endfor %}
</ul>
<a href="{% url 'blog:detail' question.id %}"> Vote again? </a>
</body>
</html>